# Generated by Django 2.0.13 on 2020-06-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_auto_20200622_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(choices=[('USD', 'United State Dollar'), ('EUR', 'Euro')], max_length=128, verbose_name='Валюта'),
        ),
    ]
